# Generated by Django 4.2.1 on 2023-05-10 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0002_rename_description_category_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="department",
            name="department_id",
        ),
        migrations.RemoveField(
            model_name="location",
            name="location_id",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="subcategory_id",
        ),
    ]
